import numpy as np
import matplotlib.pyplot as plt
import TuDo_analytix.XES as XES
import glob

plt.close("all")
plt.ion()
el_path=sorted(glob.glob("XES_elastic_pics/" + "*.tif"))
#path to elastic images or spanish path
spec_path=sorted(glob.glob("XES_spect_pics/" + "*.tif"))
ref_path=sorted(glob.glob("XES_ref_pics/" + "*.tif"))
#path to spectra images

test_elastic=XES.XES_elastics(el_path, np.linspace(10500,10680,7))
#generate elastics_object
test_elastic.calc_params()
#calculate params for energy calibration
#default is m=1 and b=0 to see intensity to pixel
test_spect=XES.XES_object(spec_path, test_elastic)
test_ref=XES.XES_object(ref_path, test_elastic)
#generate spectrum object

test_spect.auto_rois(roiwidth=5)
test_ref.auto_rois(roiwidth=5)
#get automatic rois by searching the maximum pixels with minimum distance of 10
#rois are maximumpeaks +- the roiwidth
#works for this dataset but needs to be used carefully
#alternative test_spect.rois=[[roi1,roi2],[roi1,roi2],...]
test_spect.show_rois()
#shows rois on summed up detectorimages
test_spect.calc_spectrum_all(bgrwidth=3, bgrfit=10)
test_ref.calc_spectrum_all(bgrwidth=3, bgrfit=10)
#calculate spetrum from all images
#background is generated by rois up and down of signalrois
#background is interpolated to polynom of order 10
test_spect.spectrum=test_spect.spectrum.n(7020,7120)
test_ref.spectrum=test_ref.spectrum.n(7020,7120)
#normalize spectrum to area between 7020eV and 7120eV
test_spect.check_all_images(roiwidth=5, bgrwidth=3)
#plots all detectorimages with rois and spectra

iad_ref=test_spect.calc_IAD(test_ref.spectrum)
print(test_spect.calc_M1())
print(test_ref.calc_M1())

plt.figure()
plt.plot(test_spect.spectrum.x,test_spect.spectrum.y,color="C0")
plt.plot(test_ref.spectrum.x,test_ref.spectrum.y,color="C1",label="IAD: "+str(iad_ref))
plt.plot(test_spect.spectrum.x,(test_spect.spectrum-test_ref.spectrum).y-0.05,color="C1")
plt.xlim([7020,7080])
plt.legend()